language: python

python:
  - 3.6

cache: pip

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: parse
      name: parse all
      script:
        - python3 -m catparser --schema ./symbol/all.cats --include ./symbol
        - python3 -m catparser --schema ./nem/all.cats --include ./nem
