name: build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: mkdir dist
            - run: pip install -r requirements.txt
            - run: python3 -m catparser --schema symbol/all.cats --include symbol --output  dist/symbol.yml
            - run: python3 -m catparser --schema nem/all.cats --include nem --output  dist/nem.yml
